layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    - 

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Data Science
    web_url: https://datascience.ucsd.edu/
    image_url: https://datascience.ucsd.edu/wp-content/uploads/2019/08/UCSanDiego_Halicioglu_BlueGold.png

  - name: COVID-19 ABM Modeling
    web_url: https://geoact.sdsc.edu/
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLxOGrP744xcpnNTDFZ6DCnYzXhGTPpqG0EdDWUI0r8oz1s21BqFaRL6-oOeD25lpcVhc&usqp=CAU

  - name: Systems Engineering
    web_url: https://www.nasa.gov/seh/index.html
    image_url: https://www.simventions.com/wp-content/uploads/2015/08/Icon_SysEng.png

  - name: Aerospace
    web_url: https://www.nasa.gov/
    image_url: https://logos-world.net/wp-content/uploads/2020/05/NASA-Logo.png
    
