layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  # set github actions to push changes once per day to 3 projects
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
    - 

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  # link to most recent blog post
  - name: Data Science
    web_url: 
    image_url: 
    
  # link to my embroidery page of the website
  - name: Embroidery
    web_url: 
    image_url: 

  # link to my cooking page of the website
  - name: Cooking
    web_url: 
    image_url: 