layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    - 

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

# topics:
#   - name: Data Science
#     web_url: https://github.com/topics/css
#     image_url:

#   - name: Artificial Intelligence
#     web_url: https://github.com/topics/sass
#     image_url:

#   - name: Systems Engineering
#     web_url: https://www.nasa.gov/seh/index.html
#     image_url:

#   - name: Aerospace
#     web_url: https://github.com/topics/sass
#     image_url:

#   - name: Artificial Intelligence
#     web_url: https://github.com/topics/sass
#     image_url:
